# Site settings
title: bb123n4's blog
email: bb123n4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I think my blog is and will be super awesome （牛逼，ヤバイ）
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bb123n4.github.io/" # the base hostname & protocol for your site
github_username:  bb123n4
# Build settings
markdown: kramdown
plugins:
  - jekyll-archives


#jekyll-archives configs
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
